name: Generate-PDF

on: push

jobs:
 generate-pdf:
   name: Generate pdf with thesis
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
   - name: Compile LaTeX document
     uses: xu-cheng/latex-action@v2
     with:
       root_file: master-s-thesis.tex
   - name: Upload the document
     uses: actions/upload-artifact@v2
     with:
       name: PDF
       path: master-s-thesis.pdf